spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ollama-db
    username: ${dbName}
    password: ${dbPassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect